### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by qixiabanyi** [zhongwen-4/nonebot-plugin-picsetu#1]
发送关键词时提示keyerror
![屏幕截图 2024-10-29 203251](https://github.com/user-attachments/assets/cac093ff-934a-4c0a-b905-3343f8dd5577)

**Comment by zhongwen-4** [comment]
> 发送关键词时提示keyerror ![屏幕截图 2024-10-29 203251](https://private-user-images.githubusercontent.com/175698330/381124391-cac093ff-934a-4c0a-b905-3343f8dd5577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDU5OTAsIm5iZiI6MTczMDIwNTY5MCwicGF0aCI6Ii8xNzU2OTgzMzAvMzgxMTI0MzkxLWNhYzA5M2ZmLTkzNGEtNGMwYS1iOTA1LTMzNDNmOGRkNTU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxMjQxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQ2ZTYxNzAwMTgxM2IwNDJlYTM2NTE0YmJiYTk4MWJmZTBmY2I0MmVmZmU5OWNhMjNlNjMzY2I1YzQ3NzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yMiUhyDVPtqls7z6T-gATGHFsxa6FNfr2H7VZcFZnCw)

一直这样吗

**Comment by qixiabanyi** [comment]
第一次使用就这样
如果可以的话，希望可以添加关键词系统
&nbsp;


3479637514
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月29日(星期二) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhongwen-4/nonebot-plugin-picsetu] keyerror (Issue #1)














  
发送关键词时提示keyerror 
  
一直这样吗

**Comment by zhongwen-4** [comment]
已修复，那个关键词系统不好做，就不做了（）
